route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: "AlertManager"
        channel: "#alert"
        api_url: "incomeing-webhook-url" # needs to install incoming-webhook app on slack
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
